"""baseline schema

Creates the whole schema on an empty database, and does nothing on one that
already has it.

That second case is not hypothetical: the production database was built by
Prisma before the Python port, so its tables, enums, constraints and the partial
index all already exist — it simply has no `alembic_version` row saying so. A
plain CREATE TABLE baseline would fail the very first deploy with "relation
already exists".

`op.get_bind()` is inspected rather than trusting an environment flag, so the
same migration is correct for a fresh clone, a throwaway test container, and the
adopted production database, with no manual `alembic stamp` step to remember.

Revision ID: 9bfb11a52e4a
Revises:
Create Date: 2026-08-23 03:06:09.523170

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bfb11a52e4a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _schema_already_exists() -> bool:
    """
    True when this database predates Alembic — i.e. Prisma built it.

    Keyed on ShowSeat because it is the table everything else hangs off; a
    database with ShowSeat but not the rest would be broken in a way no
    migration should try to paper over.
    """
    return sa.inspect(op.get_bind()).has_table("ShowSeat")


def upgrade() -> None:
    """Upgrade schema."""
    if _schema_already_exists():
        # Adopting a Prisma-built database. Alembic records this revision as
        # applied and the schema is left exactly as it is.
        print("[alembic] existing schema detected — adopting it as the baseline")
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("passwordHash", sa.Text(), nullable=False),
        sa.Column(
            "role", postgresql.ENUM("CUSTOMER", "ORGANISER", "ADMIN", name="Role"), nullable=False
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("createdAt", postgresql.TIMESTAMP(precision=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "Venue",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Event",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("organiserId", sa.Text(), nullable=False),
        sa.Column("venueId", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("type", postgresql.ENUM("MOVIE", "CONCERT", name="EventType"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organiserId"],
            ["User.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venueId"],
            ["Venue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Seat",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("venueId", sa.Text(), nullable=False),
        sa.Column("section", sa.Text(), nullable=False),
        sa.Column("row", sa.Text(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("posX", sa.Numeric(asdecimal=False), nullable=False),
        sa.Column("posY", sa.Numeric(asdecimal=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["venueId"],
            ["Venue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venueId", "section", "row", "number", name="Seat_venue_label_key"),
    )
    op.create_table(
        "SeatCategory",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("eventId", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=65, scale=30), nullable=False),
        sa.Column("sections", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["eventId"],
            ["Event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("eventId", "name", name="SeatCategory_event_name_key"),
    )
    op.create_table(
        "Show",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("eventId", sa.Text(), nullable=False),
        sa.Column("startsAt", postgresql.TIMESTAMP(precision=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["eventId"],
            ["Event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Booking",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("reference", sa.Text(), nullable=False),
        sa.Column("customerId", sa.Text(), nullable=False),
        sa.Column("showId", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("CONFIRMED", "CANCELLED", name="BookingStatus"),
            nullable=False,
        ),
        sa.Column("qrToken", sa.Text(), nullable=False),
        sa.Column("createdAt", postgresql.TIMESTAMP(precision=3), nullable=False),
        sa.Column("cancelledAt", postgresql.TIMESTAMP(precision=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["customerId"],
            ["User.id"],
        ),
        sa.ForeignKeyConstraint(
            ["showId"],
            ["Show.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("qrToken"),
        sa.UniqueConstraint("reference"),
    )
    op.create_index(
        "Booking_customerId_createdAt_idx", "Booking", ["customerId", "createdAt"], unique=False
    )
    op.create_table(
        "ShowSeat",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("showId", sa.Text(), nullable=False),
        sa.Column("seatId", sa.Text(), nullable=False),
        sa.Column("categoryId", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("AVAILABLE", "HELD", "OFFERED", "BOOKED", name="SeatStatus"),
            nullable=False,
        ),
        sa.Column("heldByUserId", sa.Text(), nullable=True),
        sa.Column("holdExpiresAt", postgresql.TIMESTAMP(precision=3), nullable=True),
        sa.Column("offerExpiresAt", postgresql.TIMESTAMP(precision=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["categoryId"],
            ["SeatCategory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seatId"],
            ["Seat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["showId"],
            ["Show.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("showId", "seatId", name="ShowSeat_show_seat_key"),
    )
    op.create_index("ShowSeat_showId_status_idx", "ShowSeat", ["showId", "status"], unique=False)
    op.create_table(
        "WaitlistEntry",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("showId", sa.Text(), nullable=False),
        sa.Column("categoryId", sa.Text(), nullable=False),
        sa.Column("customerId", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "WAITING", "OFFERED", "EXPIRED", "CONVERTED", "CANCELLED", name="WaitlistStatus"
            ),
            nullable=False,
        ),
        sa.Column("joinedAt", postgresql.TIMESTAMP(precision=3), nullable=False),
        sa.Column("offeredSeatId", sa.Text(), nullable=True),
        sa.Column("offerToken", sa.Text(), nullable=True),
        sa.Column("offerExpiresAt", postgresql.TIMESTAMP(precision=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["categoryId"],
            ["SeatCategory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customerId"],
            ["User.id"],
        ),
        sa.ForeignKeyConstraint(
            ["showId"],
            ["Show.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("offerToken"),
    )
    op.create_index(
        "WaitlistEntry_queue_idx",
        "WaitlistEntry",
        ["showId", "categoryId", "status", "joinedAt"],
        unique=False,
    )
    op.create_table(
        "BookingSeat",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("bookingId", sa.Text(), nullable=False),
        sa.Column("showSeatId", sa.Text(), nullable=False),
        sa.Column("priceAtBooking", sa.Numeric(precision=65, scale=30), nullable=False),
        sa.Column("releasedAt", postgresql.TIMESTAMP(precision=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["bookingId"],
            ["Booking.id"],
        ),
        sa.ForeignKeyConstraint(
            ["showSeatId"],
            ["ShowSeat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bookingId", "showSeatId", name="BookingSeat_booking_seat_key"),
    )
    op.create_index("BookingSeat_showSeatId_idx", "BookingSeat", ["showSeatId"], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------ seatbelt
    # A PARTIAL unique index, which the declarative layer cannot express — so it
    # is written by hand here and must survive every future autogenerate.
    #
    # BookingSeat.showSeatId is deliberately NOT plainly unique (ADR-020): a
    # plain unique constraint made a cancelled seat unsellable forever, because
    # the cancelled booking's row still claimed it. Guarding only the rows where
    # releasedAt IS NULL means at most one *live* claim per seat while the dead
    # ones stay for revenue history.
    #
    # If a future `alembic revision --autogenerate` proposes dropping this, that
    # is drift, not an improvement. See docs/DEBUGGING.md.
    op.execute(
        """
        CREATE UNIQUE INDEX "BookingSeat_showSeatId_live_key"
            ON "BookingSeat"("showSeatId") WHERE "releasedAt" IS NULL
        """
    )


def downgrade() -> None:
    """
    Drops everything.

    Deliberately NOT conditional. Adopting a database silently is safe; dropping
    one silently is not, so a downgrade run against production does exactly what
    it says on the tin and the operator gets what they asked for.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS "BookingSeat_showSeatId_live_key"')
    op.drop_index("BookingSeat_showSeatId_idx", table_name="BookingSeat")
    op.drop_table("BookingSeat")
    op.drop_index("WaitlistEntry_queue_idx", table_name="WaitlistEntry")
    op.drop_table("WaitlistEntry")
    op.drop_index("ShowSeat_showId_status_idx", table_name="ShowSeat")
    op.drop_table("ShowSeat")
    op.drop_index("Booking_customerId_createdAt_idx", table_name="Booking")
    op.drop_table("Booking")
    op.drop_table("Show")
    op.drop_table("SeatCategory")
    op.drop_table("Seat")
    op.drop_table("Event")
    op.drop_table("Venue")
    op.drop_table("User")
    # ### end Alembic commands ###
